--  - This is from 837 Tables.sql

CALL EDIDB2A.SP_UTIL_DROP( 'TABLE EDIDB2A.T_277CA_FILE_PCES_LOG');

CREATE TABLE EDIDB2A.T_277CA_FILE_PCES_LOG
(
	FILE_ID				BIGINT NOT NULL ,
	PRNT_FILE_ID		BIGINT ,
	MAS_FILE_ID			BIGINT,
	FILE_NME			VARCHAR(255) ,
	FILE_ROOT_DTRY_TXT	VARCHAR(75),
	FILE_SUB_DTRY_TXT	VARCHAR(50),
	FILE_VER_ID			VARCHAR(8),
	FILE_SIZE_CNT		BIGINT,
	FILE_STT_CD			CHAR(2) DEFAULT	'V',
	FILE_FMT_CD			CHAR(1) DEFAULT 'A',
	DIR_CD				CHAR(1) DEFAULT	'I',
	FILE_TYPE_CD		CHAR(1) DEFAULT	'A',
	FILE_ORGN_CD		CHAR(1) DEFAULT	'E',
	TEST_CD				CHAR(1) DEFAULT	'P',
	DEL_CD				CHAR(1) DEFAULT 'N',
	TOTAL_ACCEPTED		INTEGER,
	TOTAL_REJECTED		INTEGER,
	TOTAL_ACCEPTED_AMT	DECIMAL(15,2),
	TOTAL_REJECTED_AMT	DECIMAL(15,2),
	APP_TRACE_ID		VARCHAR(50),
	RECV_TS				TIMESTAMP,
	PCES_TS				TIMESTAMP,
	ISA_CTRL_NUM		INTEGER,
	SNDR_ID				VARCHAR(15),
	DEL_TS				TIMESTAMP,
	RESUBM_CD			CHAR(1) DEFAULT 'N',
	RESUBM_TS			TIMESTAMP
)IN TBSP_TABLES index IN TBSP_INDEX;

ALTER TABLE EDIDB2A.T_277CA_FILE_PCES_LOG	ADD CONSTRAINT  X_277CA_FILE_PCS_LOG PRIMARY KEY (FILE_ID);


CALL EDIDB2A.SP_UTIL_DROP( 'TABLE EDIDB2A.T_277CA_CLM_CTRL_LOG');

CREATE TABLE EDIDB2A.T_277CA_CLM_CTRL_LOG
(
	CLM_ID		BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY 
				(  	START WITH +100000001 	INCREMENT BY +1  
					MINVALUE   +100000000  	MAXVALUE +9223372036854775807  
					NO CYCLE  CACHE 240  NO ORDER 
				),
	FILE_ID		BIGINT ,
	PAYR_PAT_ACCT_NUM	VARCHAR(38) , -- CLM01 Patient Account No.
	PAYR_TRC_NUM 		VARCHAR(20) , -- REF-D9 Clearing House Trace No.
	PAYR_CLM_CTRL_NO	VARCHAR(15) , -- REF 1K Payer Claim Control No.
	SUBM_TRC_NUM		VARCHAR(20) , -- Cross Reference back to the Submitter Provided REF D9
	ORIG_CLM_ID			BIGINT,	  -- References CLM_ID in T_837P_CLM_CTRL_LOG
	CLM_AMT				DECIMAL(15,2),
	CLM_STT_CD			CHAR(4),
	TEST_CD				CHAR(1) DEFAULT	'P',
	DEL_CD				CHAR(1) DEFAULT 'N',
	DEL_TS				TIMESTAMP,
	RESUBM_CD			CHAR(1) DEFAULT 'N',
	RESUBM_TS			TIMESTAMP
)IN TBSP_TABLES index IN TBSP_INDEX;

ALTER TABLE EDIDB2A.T_277CA_CLM_CTRL_LOG	ADD CONSTRAINT  X_277CA_CLM_CTRL_LOG PRIMARY KEY (CLM_ID);

--=============================================================================
--	Author:			Venkata Chalam Pasala
--	Date:			Sep/24/2010
--	Description:	Contains all the Table Definitions related to the 277CA
--					Transaction For Inbound 277CA.
--=============================================================================

CALL EDIDB2A.SP_UTIL_DROP( 'TABLE EDIDB2A.T_277CA_SRC');
CALL EDIDB2A.SP_UTIL_DROP( 'TABLE EDIDB2A.T_277CA_RECR');
CALL EDIDB2A.SP_UTIL_DROP( 'TABLE EDIDB2A.T_277CA_BILL_PROV');
CALL EDIDB2A.SP_UTIL_DROP( 'TABLE EDIDB2A.T_277CA_PAT ');
CALL EDIDB2A.SP_UTIL_DROP( 'TABLE EDIDB2A.T_277CA_CLM');
CALL EDIDB2A.SP_UTIL_DROP( 'TABLE EDIDB2A.T_277CA_SRVLN');
CALL EDIDB2A.SP_UTIL_DROP( 'TABLE EDIDB2A.T_277CA_STC');

--=============================================================================
--	Table used to contain the details of the Source of this Transaction
--	Note: The ID for this table will be generated by the SPLIT_277CA Map
--=============================================================================
CREATE TABLE T_277CA_SRC
(
	ID					BIGINT NOT NULL,
	FILE_ID				BIGINT,
	DIR_CD				CHAR(1) DEFAULT	'I',
	REF_ID_BHT03		VARCHAR(50)  NOT NULL,	-- BHT03
	CREA_DT_BHT04		DATE  ,					-- BHT04
	ENTY_ID_CD_NM101	CHAR(3)  ,				-- Loop 2100A - NM101
	ORG_NME_NM103		VARCHAR(60)  ,			-- Loop 2100A - NM103
	IDN_CD_QLFR_NM108	CHAR(2)  ,				-- Loop 2100A - NM108
	IDN_CD_NM109		VARCHAR(80)  ,			-- Loop 2100A - NM109
	APPL_TRC_NUM_TRN02	VARCHAR(50)  ,			-- Loop 2200A - TRN-TRN01=02
	RCP_DT_DTP03		DATE  ,					-- Loop 2200A -	DTP-DTO01=050
	PCES_DT_DTP03		DATE  					-- Loop 2200A -	DTP-DTO01=009
) IN TBSP_TABLES INDEX IN TBSP_INDEX ;
ALTER TABLE T_277CA_SRC  ADD CONSTRAINT  XPKT_277CA_Source  PRIMARY KEY (REF_ID_BHT03) ;

--=============================================================================
--	Table used to contain the details of the Receiver of this Transaction
--=============================================================================
CREATE TABLE T_277CA_RECR
(
	ID  					BIGINT  NOT NULL,
	FILE_ID					BIGINT,
	DIR_CD					CHAR(1) DEFAULT	'I',
	ET_QLFR_NM102  			CHAR(3)  ,			-- Loop 2100B - NM102
	ORG_NME_NM103  			VARCHAR(60)  ,		-- Loop 2100B - NM103
	FST_NME_NM104  			VARCHAR(35)  ,		-- Loop 2100B - NM104
	MID_NME_NM105  			VARCHAR(25)  ,		-- Loop 2100B - NM105
	ID_CD_NM109  			VARCHAR(80)  ,		-- Loop 2100B - NM109
	CLM_TRAN_BAT_NUM_TRN02  VARCHAR(50)  ,		-- Loop 2200B - TRN-TRN01=02
	ACPD_QTY_QTR  			INTEGER  ,			-- Loop 2200B - QTY-QTY01=90(Accepted Quantity)
	REJ_QTY_QTR  			INTEGER  ,			-- Loop 2200B - QTY-QTY01=AA(Rejected Quantity)
	ACPD_AMT  				DECIMAL(18,2),		-- Loop 2200B - AMT-AMT01=YU
	REJ_AMT  				DECIMAL(18,2)  		-- Loop 2200B - AMT-AMT01=YY
) IN TBSP_TABLES INDEX IN TBSP_INDEX ;

ALTER TABLE T_277CA_RECR  ADD CONSTRAINT  XPKT_277CA_Receive  PRIMARY KEY (ID) ;

--=============================================================================
--	Billing Provider Details
--	Note: The ID for this table will be generated by the SPLIT_277CA Map
--=============================================================================
CREATE TABLE T_277CA_BILL_PROV
(
	ID            			BIGINT  NOT NULL,
	FILE_ID					BIGINT,
	RECR_ID					BIGINT,				-- References ID from T_277CA_RECR
	ET_QLFR__NM102  		CHAR(3)  ,			-- Loop 2100C, NM102
	ORG_NME_NM103   		VARCHAR(60)  ,		-- Loop 2100C, NM103
	FST_NME_NM104   		VARCHAR(35)  ,		-- Loop 2100C, NM104
	MID_NME_NM105   		VARCHAR(25)  ,		-- Loop 2100C, NM105
	IDN_CD_QLFR_NM108  		CHAR(2)  ,			-- Loop 2100C, NM108
	IDN_CD_NM109  			VARCHAR(80)  ,		-- Loop 2100C, NM109
	SERV_INFO_TRC_NUM_TRN02	VARCHAR(50)  ,		-- Loop 2200C, TRN02
	STATE_LIC_NUM_REF0B		CHAR(20),			-- Loop 2200C, REF-REF01=0B
	PROV_UPIN_NUM_REFIG		CHAR(20),			-- Loop 2200C, REF-REF01=1G
	PROV_COM_NUM_REFG2		CHAR(20),			-- Loop 2200C, REF-REF01=G2
	LOC_NUM_REFLU			CHAR(20),			-- Loop 2200C, REF-REF01=LU
	SSN_REFSY				CHAR(20),			-- Loop 2200C, REF-REF01=SY
	FED_TIN_REFTJ			CHAR(20),			-- Loop 2200C, REF-REF01=TJ
	ACPD_QTY_QTRQA  		INTEGER  ,			-- Loop 2200C, QTY-QTY01=QA
	REJ_QTY_QTRQC  			INTEGER  ,			-- Loop 2200C, QTY-QTY01=QC
	ACPD_AMT_AMTYU  		DECIMAL(18,2)  ,	-- Loop 2200C, AMT-AMT01=YU
	REJ_AMT_AMTYY  			DECIMAL(18,2)  		-- Loop 2200C, AMT-AMT01=YY
) IN TBSP_TABLES INDEX IN TBSP_INDEX ;
ALTER TABLE T_277CA_BILL_PROV ADD CONSTRAINT  XPKT_277_Billing_P  PRIMARY KEY (ID) ;

--=============================================================================
--	Note: The ID for this table will be generated by the SPLIT_277CA Map
--=============================================================================
CREATE TABLE T_277CA_PAT
(
	ID					BIGINT  NOT NULL,
	FILE_ID				BIGINT,
	RECR_ID				BIGINT,					-- References ID from T_277CA_RECR
	BILL_PROV_ID		BIGINT,					-- References ID from T_277CA_BILL_PROV
	LST_NME  			VARCHAR(60)  ,			-- Loop 2100D - NM103	
	FST_NME  			VARCHAR(35)  ,			-- Loop 2100D - NM104
	MID_NME  			VARCHAR(35)  ,			-- Loop 2100D - NM105
	NME_SFX  			VARCHAR(10)  ,			-- Loop 2100D - NM107
	PAT_ID_QLFR  		CHAR(2)  ,				-- Loop 2100D - NM108
	PAT_ID  			VARCHAR(80)  NOT NULL	-- Loop 2100D - NM109
) IN TBSP_TABLES INDEX IN TBSP_INDEX ;
ALTER TABLE T_277CA_PAT ADD CONSTRAINT  XPKT_277CA_Patient  PRIMARY KEY (ID) ;

--=============================================================================
--	Note: The ID for this table will be generated by the SPLIT_277CA Map
--=============================================================================

CREATE TABLE T_277CA_CLM
(
	ID  					BIGINT  NOT NULL,
	FILE_ID					BIGINT,
	RECR_ID					BIGINT,				-- References ID from T_277CA_RECR
	BILL_PROV_ID			BIGINT,				-- References ID from T_277CA_BILL_PROV
	PATIENT_ID				BIGINT,				-- References ID from T_277CA_PAT
	PAT_CTRL_NUM_CLM01		VARCHAR(20)  ,		-- Loop 2200D, TRN02 - TRN01=2
	PAYR_CTRL_NUM_REF1K		VARCHAR(50)  ,		-- Loop 2200D, REF - REF01=1K
	CLR_HOUSE_TRC_NUM_REFD9	VARCHAR(30),		-- Loop 2200D, REF - REF01=D9
	BILL_TYPE_ID_REFBLT		VARCHAR(50),		-- Loop 2200D, REF - REF01=BLT
	SERV_FR_DT				DATE  ,				-- Loop 2200D, FROM DATE(DTP03) - DTP01=472
	SERV_TO_DT  			DATE  ,				-- Loop 2200D, TO DATE(DTP03) - DTP01=472
	OUT_REFD9				VARCHAR(30),		-- Populate this Field with Lookup into REFD9 Table using(CLR_HOUSE_TRC_NUM_REFD9)
	OUT_TP_QLFR				CHAR(2),			-- Populate this field with 837 File/ISA05 of the File from which this Claim was Received
	OUT_TP_ID 				VARCHAR(15),		-- Populate this field with 837 File/ISA06 of the File from which this Claim was Received
	OUT_TP_ID				BIGINT,				-- Populate this field with the TPID of the Trading Partner from which this calim was received
	OUT_RECR_ID				BIGINT,				-- References the Outbound Receiver Record(New records will be created)
	OUT_SRC_ID				BIGINT				-- References the Outbound Source Record(New Records will be created)
) IN TBSP_TABLES INDEX IN TBSP_INDEX;
ALTER TABLE T_277CA_CLM  ADD CONSTRAINT  XPKT_277CA_Claim  PRIMARY KEY (ID) ;

--=============================================================================
--	Contains the Service Lines corresponding to the Claims as part of 277CA
--	Note: The ID for this table will be generated by the SPLIT_277CA Map
--=============================================================================

CREATE TABLE T_277CA_SRVLN
(
	ID  					BIGINT  NOT NULL,
	FILE_ID					BIGINT,
	RECR_ID					BIGINT,				-- References ID from T_277CA_RECR
	BILL_PROV_ID			BIGINT,				-- References ID from T_277CA_BILL_PROV
	PATIENT_ID				BIGINT,				-- References ID from T_277CA_PAT
	CLM_ID					BIGINT,				-- References ID from T_277CA_CLM
	PROC_CD_QLFR  			CHAR(2)  ,			-- Loop 2220D, SVC01-1
	PROC_CD  				VARCHAR(48)  ,		-- Loop 2220D, SVC01-2
	PROC_MOD1  				CHAR(2)  ,			-- Loop 2220D, SVC01-3
	PROC_MOD2  				CHAR(2)  ,			-- Loop 2220D, SVC01-4
	PROC_MOD3  				CHAR(2)  ,			-- Loop 2220D, SVC01-5
	PROC_MOD4  				CHAR(2)  ,			-- Loop 2220D, SVC01-6
	LINE_AMT  				DECIMAL(18,2)  ,	-- Loop 2220D, SVC02
	LINE_REV_CD				VARCHAR(48),		-- Loop 2220D, SVC04
	UNIT_OF_SVC				DECIMAL(15,2),		-- Loop 2220D, SVC07
	LINE_ITEM_CTRL_NUM_R  	VARCHAR(50)  ,		-- Loop 2220D, REF-REF01=FJ
	PHRM_PRSC_NUM_REF_XZ  	VARCHAR(50)  ,		-- Loop 2220D, REF-REF01=XZ
	SERV_FR_DT				DATE  ,				-- Loop 2220D, FROM DATE(DTP03) - DTP01=472
	SERV_TO_DT  			DATE  				-- Loop 2220D, TO DATE(DTP03) - DTP01=472
) IN TBSP_TABLES INDEX IN TBSP_INDEX ;

ALTER TABLE T_277CA_SRVLN  ADD CONSTRAINT  XPKT_277_Service_L  PRIMARY KEY (ID) ;


--=============================================================================
--	This table will contain the STC Codes related to all the Various Objects
--	STC Errors can be transmitted along with Billing Provider, Patient,
--	Claim and Service Lines and they can occur multiple time. So all of them
--	have been extracted and persisted into one common table
--	Note: The ID for this table will not be generated by the SPLIT_277CA Map
--	but will be autogenerated.
--=============================================================================
CREATE TABLE T_277CA_STC
(
	ID						BIGINT  NOT NULL GENERATED ALWAYS AS IDENTITY 
							(  	START WITH +100000000001 	INCREMENT BY +1  
							MINVALUE   +100000000001  	MAXVALUE +9223372036854775807  
							NO CYCLE  CACHE 500  NO ORDER 
							) ,
	FILE_ID					BIGINT,
	RECR_ID					BIGINT,				-- References ID from T_277CA_RECR
	BILL_PROV_ID			BIGINT,				-- References ID from T_277CA_BILL_PROV
	PATIENT_ID				BIGINT,				-- References ID from T_277CA_PAT
	CLM_ID					BIGINT,				-- References ID from T_277CA_CLM
	SRVLN_ID				BIGINT,				-- References ID from T_277CA_CLM
	STC01_1					VARCHAR(30)  ,		-- STC01-1
	STC01_2					VARCHAR(30)  ,		-- STC01-2
	STC01_3					CHAR(3)  ,			-- STC01-3
	DATE_STC02				DATE,				-- STC02
	ACT_CODE_STC03			CHAR(2),			-- STC03
	AMT_STC04				DECIMAL(18,2),		-- STC04
	STC10_1  				VARCHAR(30)  ,		-- STC10-1
	STC10_2  				VARCHAR(30)  ,		-- STC10-2
	STC10_3  				CHAR(3)  ,			-- STC10-3
	STC11_1  				VARCHAR(30)  ,		-- STC11-1
	STC11_2  				VARCHAR(30)  ,		-- STC11-2
	STC11_3  				CHAR(3)  ,			-- STC11-3
	STC12  					VARCHAR(264)  		-- STC12
)IN TBSP_TABLES INDEX IN TBSP_INDEX ;

ALTER TABLE T_277CA_STC  ADD CONSTRAINT  XPKT_277CA_STC  PRIMARY KEY (ID) ;